# Generated by Django 3.1.2 on 2021-04-07 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='areas',
            fields=[
                ('areas_id', models.AutoField(primary_key=True, serialize=False)),
                ('areas_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='categorys',
            fields=[
                ('categorys_id', models.AutoField(primary_key=True, serialize=False)),
                ('categorys_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categorys',
            },
        ),
        migrations.CreateModel(
            name='docters',
            fields=[
                ('docters_id', models.AutoField(primary_key=True, serialize=False)),
                ('docters_image', models.CharField(max_length=250)),
                ('docters_name', models.CharField(max_length=50)),
                ('docters_no', models.IntegerField()),
                ('hospital_name', models.CharField(max_length=50)),
                ('hospital_no', models.IntegerField()),
                ('hospital_address', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'docters',
            },
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('payments_id', models.AutoField(primary_key=True, serialize=False)),
                ('payments_types', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('products_id', models.AutoField(primary_key=True, serialize=False)),
                ('products_name', models.CharField(max_length=50)),
                ('products_image', models.CharField(max_length=150)),
                ('products_price', models.CharField(max_length=9)),
                ('products_quantity', models.IntegerField()),
                ('products_description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='states',
            fields=[
                ('states_id', models.AutoField(primary_key=True, serialize=False)),
                ('states_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('users_id', models.AutoField(primary_key=True, serialize=False)),
                ('users_password', models.CharField(max_length=15)),
                ('users_email', models.EmailField(max_length=150)),
                ('mobile_no', models.IntegerField()),
                ('birth_of_date', models.DateField()),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('is_admin', models.IntegerField()),
                ('otp', models.CharField(max_length=10, null=True)),
                ('otp_used', models.IntegerField()),
                ('areas_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.areas')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='wishlists',
            fields=[
                ('wishlists_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_date', models.DateField()),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.products')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.users')),
            ],
            options={
                'db_table': 'wishlists',
            },
        ),
        migrations.CreateModel(
            name='sub_categorys',
            fields=[
                ('sub_categorys_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_categorys_name', models.CharField(max_length=50)),
                ('categorys_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.categorys')),
            ],
            options={
                'db_table': 'sub_categorys',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='sub_categorys_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.sub_categorys'),
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('orders_id', models.AutoField(primary_key=True, serialize=False)),
                ('orders_date', models.DateField()),
                ('total_amount', models.FloatField()),
                ('orders_status', models.IntegerField()),
                ('payments_status', models.IntegerField()),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.users')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='order_items',
            fields=[
                ('order_items_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_quantity', models.IntegerField()),
                ('order_amount', models.IntegerField()),
                ('oreder_total', models.IntegerField()),
                ('orders_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.orders')),
            ],
            options={
                'db_table': 'order items',
            },
        ),
        migrations.CreateModel(
            name='gallerys',
            fields=[
                ('gallerys_id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.CharField(max_length=150)),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.products')),
            ],
            options={
                'db_table': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='feedbacks',
            fields=[
                ('feedbacks_id', models.AutoField(primary_key=True, serialize=False)),
                ('suggestion_date', models.DateField()),
                ('suggestion', models.CharField(max_length=200)),
                ('rate', models.IntegerField(verbose_name=5)),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.products')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.users')),
            ],
            options={
                'db_table': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='citys',
            fields=[
                ('citys_id', models.AutoField(primary_key=True, serialize=False)),
                ('citys_name', models.CharField(max_length=30)),
                ('states_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.states')),
            ],
            options={
                'db_table': 'citys',
            },
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('amount', models.FloatField()),
                ('added_date', models.DateField()),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.users')),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.AddField(
            model_name='areas',
            name='citys_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.citys'),
        ),
    ]
