# Generated by Django 3.1.2 on 2021-04-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20210407_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='products_price',
            field=models.IntegerField(max_length=9),
        ),
    ]
