# Generated by Django 3.1.2 on 2021-04-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20210407_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='products_price',
            field=models.IntegerField(),
        ),
    ]
