# Generated by Django 3.1.2 on 2021-04-07 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20210407_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='products_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='applications.products'),
            preserve_default=False,
        ),
    ]
