# Generated by Django 3.1.2 on 2021-04-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_order_items_products_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='users_password',
            field=models.CharField(max_length=150),
        ),
    ]
