# Generated by Django 3.1.2 on 2021-04-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20210409_1618'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order_items',
            table='orderitems',
        ),
    ]
