# Generated by Django 3.1.2 on 2021-04-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_auto_20210420_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='products_name',
            field=models.CharField(max_length=150),
        ),
    ]
